// watch records — 12 watches across all brands & collections
const Brand      = require('../models/Brand')
const Collection = require('../models/Collection')
const Watch      = require('../models/Watch')

module.exports = async () => {
    // Look up brands and collections by slug
    const [
        rolex, patek, ap, iwc,
        submariner, datejust, daytona,
        nautilus, calatrava,
        royalOak, royalOakOffshore,
        pilots, portugieser,
    ] = await Promise.all([
        Brand.findOne({ slug: 'rolex' }),
        Brand.findOne({ slug: 'patek-philippe' }),
        Brand.findOne({ slug: 'audemars-piguet' }),
        Brand.findOne({ slug: 'iwc-schaffhausen' }),
        Collection.findOne({ slug: 'rolex-submariner' }),
        Collection.findOne({ slug: 'rolex-datejust' }),
        Collection.findOne({ slug: 'rolex-daytona' }),
        Collection.findOne({ slug: 'patek-nautilus' }),
        Collection.findOne({ slug: 'patek-calatrava' }),
        Collection.findOne({ slug: 'ap-royal-oak' }),
        Collection.findOne({ slug: 'ap-royal-oak-offshore' }),
        Collection.findOne({ slug: 'iwc-pilots' }),
        Collection.findOne({ slug: 'iwc-portugieser' }),
    ])

    const watches = [
        // ── Rolex Submariner ─────────────────────────────────────
        {
            name:        'Rolex Submariner Date 41',
            slug:        'rolex-submariner-date-41',
            brand:       rolex._id,
            collection:  submariner._id,
            gender:      'men',
            price:       14500,
            category:    'dive',
            stock:       8,
            isFeatured:  true,
            description: 'The iconic diving reference in Oystersteel with a black Cerachrom bezel.',
            images:      ['/images/watches/rolex-sub-date-41.jpg'],
            specs: {
                caseMaterial:   'Oystersteel',
                caseDiameter:   '41mm',
                movement:       'Automatic (Cal. 3235)',
                powerReserve:   '70 hours',
                waterResistance:'300m',
                crystal:        'Sapphire',
                bracelet:       'Oyster',
                dialColor:      'Black',
            },
        },
        {
            name:        'Rolex Submariner No-Date',
            slug:        'rolex-submariner-no-date',
            brand:       rolex._id,
            collection:  submariner._id,
            gender:      'men',
            price:       13200,
            category:    'dive',
            stock:       5,
            isFeatured:  false,
            description: 'Pure. No date, no clutter. The purist\'s Submariner.',
            images:      ['/images/watches/rolex-sub-no-date.jpg'],
            specs: {
                caseMaterial:   'Oystersteel',
                caseDiameter:   '41mm',
                movement:       'Automatic (Cal. 3230)',
                powerReserve:   '70 hours',
                waterResistance:'300m',
                crystal:        'Sapphire',
                bracelet:       'Oyster',
                dialColor:      'Black',
            },
        },
        // ── Rolex Datejust ───────────────────────────────────────
        {
            name:        'Rolex Datejust 41 Blue Dial',
            slug:        'rolex-datejust-41-blue',
            brand:       rolex._id,
            collection:  datejust._id,
            gender:      'unisex',
            price:       12800,
            category:    'classic',
            stock:       12,
            isFeatured:  false,
            description: 'The quintessential dress watch with a stunning sunburst blue dial.',
            images:      ['/images/watches/rolex-datejust-41-blue.jpg'],
            specs: {
                caseMaterial:   'Oystersteel',
                caseDiameter:   '41mm',
                movement:       'Automatic (Cal. 3235)',
                powerReserve:   '70 hours',
                waterResistance:'100m',
                crystal:        'Sapphire',
                bracelet:       'Jubilee',
                dialColor:      'Blue',
            },
        },
        // ── Rolex Daytona ────────────────────────────────────────
        {
            name:        'Rolex Cosmograph Daytona',
            slug:        'rolex-cosmograph-daytona',
            brand:       rolex._id,
            collection:  daytona._id,
            gender:      'men',
            price:       36500,
            category:    'sport',
            stock:       3,
            isFeatured:  true,
            description: 'The most sought-after sports watch in the world. White gold, black ceramic bezel.',
            images:      ['/images/watches/rolex-daytona.jpg'],
            specs: {
                caseMaterial:   '18ct White Gold',
                caseDiameter:   '40mm',
                movement:       'Automatic (Cal. 4130)',
                powerReserve:   '72 hours',
                waterResistance:'100m',
                crystal:        'Sapphire',
                bracelet:       'Oyster',
                dialColor:      'Black',
            },
        },
        // ── Patek Philippe Nautilus ──────────────────────────────
        {
            name:        'Patek Philippe Nautilus 5711',
            slug:        'patek-nautilus-5711',
            brand:       patek._id,
            collection:  nautilus._id,
            gender:      'men',
            price:       185000,
            category:    'luxury',
            stock:       1,
            isFeatured:  true,
            description: 'The most coveted sports watch ever made. A masterpiece of integrated bracelet design.',
            images:      ['/images/watches/patek-nautilus-5711.jpg'],
            specs: {
                caseMaterial:   'Stainless Steel',
                caseDiameter:   '40mm',
                movement:       'Automatic (Cal. 26-330)',
                powerReserve:   '45 hours',
                waterResistance:'120m',
                crystal:        'Sapphire (double anti-reflective)',
                bracelet:       'Integrated Steel',
                dialColor:      'Blue',
            },
        },
        {
            name:        'Patek Philippe Nautilus 5726A Annual Calendar',
            slug:        'patek-nautilus-5726a',
            brand:       patek._id,
            collection:  nautilus._id,
            gender:      'men',
            price:       97000,
            category:    'luxury',
            stock:       2,
            isFeatured:  false,
            description: 'Annual calendar complication inside the iconic Nautilus case. Adjusts date only once a year.',
            images:      ['/images/watches/patek-nautilus-5726a.jpg'],
            specs: {
                caseMaterial:   'Stainless Steel',
                caseDiameter:   '40.5mm',
                movement:       'Automatic (Cal. 324 S QA LU)',
                powerReserve:   '45 hours',
                waterResistance:'120m',
                crystal:        'Sapphire',
                bracelet:       'Integrated Steel',
                dialColor:      'Silver Blue',
            },
        },
        // ── Patek Calatrava ─────────────────────────────────────
        {
            name:        'Patek Philippe Calatrava 5196G',
            slug:        'patek-calatrava-5196g',
            brand:       patek._id,
            collection:  calatrava._id,
            gender:      'women',
            price:       28000,
            category:    'dress',
            stock:       4,
            isFeatured:  false,
            description: 'White gold, hunter-case style. The most restrained, pure expression of watchmaking.',
            images:      ['/images/watches/patek-calatrava-5196g.jpg'],
            specs: {
                caseMaterial:   '18ct White Gold',
                caseDiameter:   '37mm',
                movement:       'Manual (Cal. 215 PS)',
                powerReserve:   '44 hours',
                waterResistance:'30m',
                crystal:        'Sapphire',
                bracelet:       'Leather Strap',
                dialColor:      'White',
            },
        },
        // ── Audemars Piguet Royal Oak ────────────────────────────
        {
            name:        'AP Royal Oak 15500ST Blue Dial',
            slug:        'ap-royal-oak-15500st-blue',
            brand:       ap._id,
            collection:  royalOak._id,
            gender:      'men',
            price:       82000,
            category:    'luxury',
            stock:       2,
            isFeatured:  true,
            description: 'The legendary octagonal bezel on a stunning petite tapisserie blue dial. A cultural icon.',
            images:      ['/images/watches/ap-royal-oak-blue.jpg'],
            specs: {
                caseMaterial:   'Stainless Steel',
                caseDiameter:   '41mm',
                movement:       'Automatic (Cal. 4302)',
                powerReserve:   '70 hours',
                waterResistance:'50m',
                crystal:        'Sapphire (double anti-reflective)',
                bracelet:       'Integrated Steel',
                dialColor:      'Blue',
            },
        },
        {
            name:        'AP Royal Oak Offshore Diver',
            slug:        'ap-royal-oak-offshore-diver',
            brand:       ap._id,
            collection:  royalOakOffshore._id,
            gender:      'men',
            price:       41000,
            category:    'dive',
            stock:       6,
            isFeatured:  false,
            description: 'The Offshore goes underwater. 300m water resistance in the most recognisable sports case ever.',
            images:      ['/images/watches/ap-roo-diver.jpg'],
            specs: {
                caseMaterial:   'Stainless Steel',
                caseDiameter:   '42mm',
                movement:       'Automatic (Cal. 3120)',
                powerReserve:   '60 hours',
                waterResistance:'300m',
                crystal:        'Sapphire',
                bracelet:       'Rubber Strap',
                dialColor:      'Black',
            },
        },
        // ── IWC Pilots ──────────────────────────────────────────
        {
            name:        'IWC Pilot\'s Watch Mark XX',
            slug:        'iwc-pilots-mark-xx',
            brand:       iwc._id,
            collection:  pilots._id,
            gender:      'men',
            price:       6800,
            category:    'pilot',
            stock:       15,
            isFeatured:  false,
            description: 'Anti-magnetic, highly legible, and built for the demands of aviation. The clean pilot\'s watch.',
            images:      ['/images/watches/iwc-mark-xx.jpg'],
            specs: {
                caseMaterial:   'Stainless Steel',
                caseDiameter:   '40mm',
                movement:       'Automatic (Cal. 35111)',
                powerReserve:   '120 hours',
                waterResistance:'60m',
                crystal:        'Sapphire',
                bracelet:       'Leather Strap',
                dialColor:      'Black',
            },
        },
        {
            name:        'IWC Big Pilot\'s Watch 43',
            slug:        'iwc-big-pilots-43',
            brand:       iwc._id,
            collection:  pilots._id,
            gender:      'men',
            price:       9200,
            category:    'pilot',
            stock:       9,
            isFeatured:  true,
            description: 'Oversized. Uncompromising. The Big Pilot commands attention with its 43mm presence.',
            images:      ['/images/watches/iwc-big-pilot-43.jpg'],
            specs: {
                caseMaterial:   'Stainless Steel',
                caseDiameter:   '43mm',
                movement:       'Automatic (Cal. 51111)',
                powerReserve:   '168 hours',
                waterResistance:'60m',
                crystal:        'Sapphire (double anti-reflective)',
                bracelet:       'Leather Strap',
                dialColor:      'Black',
            },
        },
        // ── IWC Portugieser ─────────────────────────────────────
        {
            name:        'IWC Portugieser Automatic 40',
            slug:        'iwc-portugieser-automatic-40',
            brand:       iwc._id,
            collection:  portugieser._id,
            gender:      'unisex',
            price:       8100,
            category:    'dress',
            stock:       11,
            isFeatured:  false,
            description: 'Slim, elegant, with the railway-track minute chapter ring that defines the Portugieser DNA.',
            images:      ['/images/watches/iwc-portugieser-40.jpg'],
            specs: {
                caseMaterial:   'Stainless Steel',
                caseDiameter:   '40mm',
                movement:       'Automatic (Cal. 82100)',
                powerReserve:   '60 hours',
                waterResistance:'30m',
                crystal:        'Sapphire',
                bracelet:       'Leather Strap',
                dialColor:      'White',
            },
        },
    ]

    const created = await Watch.insertMany(watches)
    console.log(`✅ Watches seeded: ${created.length}`)
    return created
}
